/** AUTHORIZATION */
export const AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST';
export const AUTH_SIGN_UP_REQUEST = 'AUTH_SIGN_UP_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/** UI STORE */
export const UI_UPDATE_SHORTCUTS = 'UI_UPDATE_SHORTCUTS';

/** DOCUMENT */

