/** LIST */
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const SET_DOCUMENT_EDITABLE = 'SET_DOCUMENT_EDITABLE';
export const RESET_DOCUMENT_EDITABLE = 'RESET_DOCUMENT_EDITABLE';

/** AUTHORIZATION */
export const SUBMIT_SIGN_IN_FORM = 'SUBMIT_SIGN_IN_FORM';
export const SUBMIT_SIGN_UP_FORM = 'SUBMIT_SIGN_UP_FORM';
export const REQUEST_USER_AUTH_DATA = 'REQUEST_USER_AUTH_DATA';

export const AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
