// flow-typed signature: 083b4ce3dfeea69cbdc46c240d19d84f
// flow-typed version: <<STUB>>/docz_v^2.3.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz/bin' {
  declare module.exports: any;
}

declare module 'docz/dist/index.esm' {
  declare module.exports: any;
}

declare module 'docz/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz/bin/index' {
  declare module.exports: $Exports<'docz/bin'>;
}
declare module 'docz/bin/index.js' {
  declare module.exports: $Exports<'docz/bin'>;
}
declare module 'docz/dist/index.esm.js' {
  declare module.exports: $Exports<'docz/dist/index.esm'>;
}
declare module 'docz/dist/index' {
  declare module.exports: $Exports<'docz/dist'>;
}
declare module 'docz/dist/index.js' {
  declare module.exports: $Exports<'docz/dist'>;
}
