// flow-typed signature: 74de008cd44e3f8141a672d98222778d
// flow-typed version: <<STUB>>/redux-saga_v1.1.3/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga/dist/io-d47abd80' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/io-f9ca3938' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core-npm-proxy.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core-npm-proxy.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers.min' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers.min' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.umd' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.umd.min' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.umd' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga/dist/io-d47abd80.js' {
  declare module.exports: $Exports<'redux-saga/dist/io-d47abd80'>;
}
declare module 'redux-saga/dist/io-f9ca3938.js' {
  declare module.exports: $Exports<'redux-saga/dist/io-f9ca3938'>;
}
declare module 'redux-saga/dist/redux-saga-core-npm-proxy.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core-npm-proxy.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-core-npm-proxy.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core-npm-proxy.esm'>;
}
declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.esmodules-browsers'>;
}
declare module 'redux-saga/dist/redux-saga-core.esmodules-browsers.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.esmodules-browsers.min'>;
}
declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects-npm-proxy.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-effects-npm-proxy.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects-npm-proxy.esm'>;
}
declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.esmodules-browsers'>;
}
declare module 'redux-saga/dist/redux-saga-effects.esmodules-browsers.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.esmodules-browsers.min'>;
}
declare module 'redux-saga/dist/redux-saga-effects.umd.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.umd'>;
}
declare module 'redux-saga/dist/redux-saga-effects.umd.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.umd.min'>;
}
declare module 'redux-saga/dist/redux-saga.umd.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.umd'>;
}
declare module 'redux-saga/dist/redux-saga.umd.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.umd.min'>;
}
